spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url:
    username:
    password:
    driver-class-name:
chat-gpt:
  key:
